name: Test

on:
  push:
    branches:
      - master
      - develop
      - level-up
  pull_request:

concurrency:
  # Cancel older, in-progress jobs from the same PR, same workflow.
  # use run_id if the job is triggered by a push to ensure
  # push-triggered jobs to not get canceled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: ApeWorX/github-action@v2
        with:
          python-version: "3.11.4"

      - name: version overrides
        run: |
          pip install git+https://github.com/apeworx/ape.git@main
          pip install git+https://github.com/apeworx/ethpm-types.git@main
          pip install git+https://github.com/apeworx/ape-foundry.git@main
          pip install git+https://github.com/antazoey/ape-vyper.git@feat/dev-message-fixes

      - name: compile
        run: ape compile --size
      - name: functional
        run: ape test tests/functional/ --gas --coverage
      - name: integration
        run: ape test tests/integration/ -s
